### ISSUE TITLE
Unified API and 64 bit Support

### ISSUE THREAD

**Issue by doubleday** [Cocos2DXNA/cocos2d-xna#467]
Howdi - I wanted to ask if there's already a time line for 64 bit support?

As far as I understood Monogame is ready...

**Comment by totallyeviljake** [comment]
As far as I can tell from the PRs and issue chatter, the MonoGame side is almost there. I haven't had any time to commit to creating the templates for the unified Apple and Windows templates. I did try creating a unified Windows template but had some problems with the swap chain background panel. 

Converting over to the unified 64bit Apple side will not be quick. Xamarin chose to pass-through some of the nuances of 64-bit rather than façade them in the .NET interfaces.

**Comment by doubleday** [comment]
Ok - thanks for the update!

If you choose to create a branch for this it would be cool to mention it here. I'd definitely join in early and test / bugfix if needed.

**Comment by totallyeviljake** [comment]
i pushed the ios_unified branch just now. This is the unified conversion of the cocos2d iOS project AND the update of our fork of MonoGame.

I tested it on the simulator for a few minutes and it worked. Give it a try and let us know how it goes.

**Comment by doubleday** [comment]
Great! Working on it now.

So far no problems but I'm testing right now. Will let you now when I find any problems.

On thing I needed to fix was the project file for ios because I work on a case sensitive file system (disk image) because I kept running into git problems.

My fork is messed up so I need to re-fork that's why I can't send you a pull request but here's the patch:
https://gist.github.com/doubleday/defb931a0a99d6986426

**Comment by totallyeviljake** [comment]
ok, i will integrate your patches when I can. thanks!

**Comment by totallyeviljake** [comment]
your gist changes have been added to the ios_unified branch

**Comment by totallyeviljake** [comment]
The PR is up for this issue. If there is a problem with our version of the ios unified implementation then open a new issue for it. Thanks!
